name = "EtherMaths"
uuid = "e9131f1e-6ff8-4b70-992e-15574141dedc"
authors = ["ChenyuBao <chenyu.bao@outlook.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = ">=1.11.0"
